estore/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('store.urls')),
    path('order/', include('order.urls')),
    path('coupon/', include('coupon.urls')),
    path('payment/', include('payment.urls')),
    path('notify/', include('notification.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from order import views

urlpatterns = [
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('cart', views.cart_view, name='cart'),
    path('remove-item/<int:pk>/', views.remove_item_from_cart, name='remove_item'),
    path('increase/<int:pk>/', views.increase_cart, name='increase'),
    path('decrease/<int:pk>/', views.decrease_cart, name='decrease'),
    path('wishlist-add/<int:pk>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('remove-coupon/', views.delete_session_data, name='remove_coupon'),
]

store/urls.py
from django.urls import path
from store import views

urlpatterns = [
    path('', views.HomeListView.as_view(), name='index'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='detail'),
    path('category/<int:pk>/', views.category_product, name='category'),
    path('quickview/<int:pk>/', views.category_quickview, name='quickview'),
]

store/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=30)
    image = models.ImageField(upload_to='category')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created', ]
        verbose_name_plural = 'Categories'


class Product(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    preview_des = models.TextField(max_length=200, verbose_name='Preview Description')
    description = models.TextField(max_length=1000, verbose_name='Description')
    image = models.ImageField(upload_to='products')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    is_stock = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_product_url(self):
        return reverse('detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created', ]

store/views.py
from django.shortcuts import render
# import models class
from store.models import Category, Product

# import Views class
from django.views.generic import ListView, DetailView

# import mixin for login required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


class HomeListView(ListView):
    model = Product
    template_name = 'store/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = Category.objects.filter(parent=None)
        return context


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'store/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cat_obj = Category.objects.get(name=self.object.category)
        context['releted_product'] = Product.objects.filter(category=cat_obj).order_by('-created')
        return context


@login_required
def category_product(request, pk):
    category = Category.objects.get(id=pk)
    cat_products = Product.objects.filter(category=category)

    context = {
        'cat_products': cat_products
    }
    return render(request, 'store/category.html', context)


@login_required
def category_quickview(request, pk):
    quickview = Product.objects.get(id=pk)
    context = {
        'quickview_item': quickview
    }
    return render(request, 'store/quickView.html', context)

templates/store/index.html
{% extends 'base.html' %}










{% block body %}








        <main class="main">


            <div class="intro-slider-container mb-5">
                <div class="intro-slider owl-carousel owl-theme owl-nav-inside owl-light" data-toggle="owl" 
                    data-owl-options='{
                        "dots": true,
                        "nav": false, 
                        "responsive": {
                            "1200": {
                                "nav": true,
                                "dots": false
                            }
                        }
                    }'>
                    <div class="intro-slide" style="background-image: url(/static/alfin/assets/images/demos/demo-4/slider/slide-1.png);">
                        <div class="container intro-content">
                            <div class="row justify-content-end">
                                <div class="col-auto col-sm-7 col-md-6 col-lg-5">
                                    <h3 class="intro-subtitle text-third">Deals and Promotions</h3><!-- End .h3 intro-subtitle -->
                                    <h1 class="intro-title">Beats by</h1>
                                    <h1 class="intro-title">Dre Studio 3</h1><!-- End .intro-title -->

                                    <div class="intro-price">
                                        <sup class="intro-old-price">$349,95</sup>
                                        <span class="text-third">
                                            $279<sup>.99</sup>
                                        </span>
                                    </div><!-- End .intro-price -->

                                    <a href="category.html" class="btn btn-primary btn-round">
                                        <span>Shop More</span>
                                        <i class="icon-long-arrow-right"></i>
                                    </a>
                                </div><!-- End .col-lg-11 offset-lg-1 -->
                            </div><!-- End .row -->
                        </div><!-- End .intro-content -->
                    </div><!-- End .intro-slide -->

                    <div class="intro-slide" style="background-image: url(/static/alfin/assets/images/demos/demo-4/slider/slide-2.png);">
                        <div class="container intro-content">
                            <div class="row justify-content-end">
                                <div class="col-auto col-sm-7 col-md-6 col-lg-5">
                                    <h3 class="intro-subtitle text-primary">New Arrival</h3><!-- End .h3 intro-subtitle -->
                                    <h1 class="intro-title">Apple iPad Pro <br>12.9 Inch, 64GB </h1><!-- End .intro-title -->

                                    <div class="intro-price">
                                        <sup>Today:</sup>
                                        <span class="text-primary">
                                            $999<sup>.99</sup>
                                        </span>
                                    </div><!-- End .intro-price -->

                                    <a href="category.html" class="btn btn-primary btn-round">
                                        <span>Shop More</span>
                                        <i class="icon-long-arrow-right"></i>
                                    </a>
                                </div><!-- End .col-md-6 offset-md-6 -->
                            </div><!-- End .row -->
                        </div><!-- End .intro-content -->
                    </div><!-- End .intro-slide -->
                </div><!-- End .intro-slider owl-carousel owl-simple -->

                <span class="slider-loader"></span><!-- End .slider-loader -->
            </div><!-- End .intro-slider-container -->













            <div class="container">
                <h2 class="title text-center mb-4">Explore Popular Categories</h2><!-- End .title text-center -->
                
                <div class="cat-blocks-container">
                    <div class="row">
                        

                    {% for category in category_list %}
                        <div class="col-6 col-sm-4 col-lg-2">
                            <a href="{% url 'category' pk=category.pk %}" class="cat-block">
                                <figure>
                                    <span>
                                        <img src="{{ category.image.url }}" alt="Category image">
                                    </span>
                                </figure>

                                <h3 class="cat-block-title">{{ category.name }}</h3><!-- End .cat-block-title -->
                            </a>
                        </div><!-- End .col-sm-4 col-lg-2 -->
                    {% endfor %}



                    </div><!-- End .row -->
                </div><!-- End .cat-blocks-container -->
            </div><!-- End .container -->





            <div class="mb-4"></div><!-- End .mb-4 -->



            <div class="mb-3"></div><!-- End .mb-5 -->

            <div class="container new-arrivals">
                <div class="heading heading-flex mb-3">
                    <div class="heading-left">
                        <h2 class="title">New Products</h2><!-- End .title -->
                    </div><!-- End .heading-left -->
                </div><!-- End .heading -->



                <div class="tab-content tab-content-carousel just-action-icons-sm">
                    <div class="tab-pane p-0 fade show active" id="new-all-tab" role="tabpanel" aria-labelledby="new-all-link">
                        <div class="owl-carousel owl-full carousel-equal-height carousel-with-shadow" data-toggle="owl" 
                            data-owl-options='{
                                "nav": true, 
                                "dots": true,
                                "margin": 20,
                                "loop": false,
                                "responsive": {
                                    "0": {
                                        "items":2
                                    },
                                    "480": {
                                        "items":2
                                    },
                                    "768": {
                                        "items":3
                                    },
                                    "992": {
                                        "items":4
                                    },
                                    "1200": {
                                        "items":5
                                    }
                                }
                            }'>



                            

                            

                           

                            

                            
                        {% for product in product_list %}
                            <div class="product product-2">
                                <figure class="product-media">
                                    <span class="product-label label-circle label-top">Top</span>
                                    <a href="product.html">
                                        <img src="{{ product.image.url }}" alt="Product image" class="product-image">
                                    </a>

                                    <div class="product-action-vertical">
                                        <a href="{% url 'add_to_wishlist' pk=product.pk %}" class="btn-product-icon btn-wishlist" title="Add to wishlist"></a>
                                    </div><!-- End .product-action -->

                                    <div class="product-action">
                                        <a href="{% url 'add_to_cart' pk=product.pk %}" class="btn-product btn-cart" title="Add to cart"><span>add to cart</span></a>
                                    </div><!-- End .product-action -->
                                </figure><!-- End .product-media -->

                                <div class="product-body">
                                    <div class="product-cat">
                                        <a href="#">{{ product.category }}</a>
                                    </div><!-- End .product-cat -->
                                    <h3 class="product-title"><a href="{{ product.get_product_url }}">{{ product.name }}</a></h3><!-- End .product-title -->
                                    <div class="product-price">
                                        ${{ product.price }}
                                    </div><!-- End .product-price -->
                                    <div class="ratings-container">
                                        <div class="ratings">
                                            <div class="ratings-val" style="width: 100%;"></div><!-- End .ratings-val -->
                                        </div><!-- End .ratings -->
                                        <span class="ratings-text">( 4 Reviews )</span>
                                    </div><!-- End .rating-container -->
                                </div><!-- End .product-body -->
                            </div><!-- End .product -->

                        {% endfor %}





                        </div><!-- End .owl-carousel -->
                    </div><!-- .End .tab-pane -->
                </div><!-- End .tab-content -->
            </div><!-- End .container -->
















            <div class="mb-5"></div><!-- End .mb-5 -->




{% endblock %}

templates/store/quickView.html
<div class="container quickView-container">
	<div class="quickView-content">
		<div class="row">
			<div class="col-lg-7 col-md-6">
				<div class="row">
					<div class="product-left">
						<a href="#one" class="carousel-dot active">
							<img src="{{quickview_item.image.url}}">
						</a>
					</div>
					<div class="product-right">
						<div class="owl-carousel owl-theme owl-nav-inside owl-light mb-0" data-toggle="owl" data-owl-options='{
	                        "dots": false,
	                        "nav": false, 
	                        "URLhashListener": true,
	                        "responsive": {
	                            "900": {
	                                "nav": true,
	                                "dots": true
	                            }
	                        }
	                    }'>
							<div class="intro-slide" data-hash="one">
	                            <img src="{{quickview_item.image.url}}" alt="Image Desc">
	                            <a href="https://www.portotheme.com/html/molla/popup/popup/fullscreen.html" class="btn-fullscreen">
                                    <i class="icon-arrows"></i>
                                </a>
		                    </div><!-- End .intro-slide -->

		                    <div class="intro-slide" data-hash="two">
	                            <img src="../../../../www.portotheme.com/html/molla/popup/assets/images/popup/quickView/2.html" alt="Image Desc">
	                            <a href="https://www.portotheme.com/html/molla/popup/popup/fullscreen.html" class="btn-fullscreen">
                                    <i class="icon-arrows"></i>
                                </a>
		                    </div><!-- End .intro-slide -->

		                    <div class="intro-slide" data-hash="three">
	                            <img src="../../../../www.portotheme.com/html/molla/popup/assets/images/popup/quickView/3.html" alt="Image Desc">
	                            <a href="https://www.portotheme.com/html/molla/popup/popup/fullscreen.html" class="btn-fullscreen">
                                    <i class="icon-arrows"></i>
                                </a>
		                    </div><!-- End .intro-slide -->

		                    <div class="intro-slide" data-hash="four">
	                            <img src="../../../../www.portotheme.com/html/molla/popup/assets/images/popup/quickView/4.html" alt="Image Desc">
	                            <a href="https://www.portotheme.com/html/molla/popup/popup/fullscreen.html" class="btn-fullscreen">
                                    <i class="icon-arrows"></i>
                                </a>
		                    </div><!-- End .intro-slide -->
		                </div>
					</div>
                </div>
			</div>
			<div class="col-lg-5 col-md-6">
				<h2 class="product-title">{{quickview_item.name}}</h2>
				<h3 class="product-price">${{quickview_item.price}}</h3>



                <p class="product-txt">{{quickview_item.preview_des}}</p>



                <div class="product-details-action">
                    <div class="details-action-wrapper">
                        <a href="{% url 'add_to_wishlist' pk=quickview_item.pk %}" class="btn-product btn-wishlist" title="Wishlist"><span>Add to Wishlist</span></a>
                    </div><!-- End .details-action-wrapper -->
                    <a href="{% url 'add_to_cart' pk=quickview_item.pk %}" class="btn-product btn-cart"><span>add to cart</span></a>
                </div>

                <div class="product-details-footer">
                    <div class="product-cat">
                        <span>Category:</span>
						<span>{{quickview_item.category}}</span>
                    </div><!-- End .product-cat -->

                    <div class="social-icons social-icons-sm">
                        <span class="social-label">Share:</span>
                        <a href="#" class="social-icon" title="Facebook" target="_blank"><i class="icon-facebook-f"></i></a>
                        <a href="#" class="social-icon" title="Twitter" target="_blank"><i class="icon-twitter"></i></a>
                        <a href="#" class="social-icon" title="Instagram" target="_blank"><i class="icon-instagram"></i></a>
                        <a href="#" class="social-icon" title="Pinterest" target="_blank"><i class="icon-pinterest"></i></a>
                    </div>
                </div>
			</div>
		</div>
	</div>
</div>